# Generated by Django 4.2.1 on 2023-06-07 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAE403', '0004_alter_compte_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
